name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Add targets
        run: rustup target add ${{ matrix.target }}

      - name: Install cross-compilation dependencies
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build (binaries)
        run: |
          cargo build --release --target ${{ matrix.target }} --bin mpris-bridged --bin mpris-bridgec

      - name: Ensure binaries exist
        run: |
          ls target/${{ matrix.target }}/release/mpris-bridged
          ls target/${{ matrix.target }}/release/mpris-bridgec

      - name: Package
        run: |
          mkdir -p dist
          TAR="mpris-bridge-${{ matrix.target }}.tar.gz"
          TDIR="target/${{ matrix.target }}/release"
          tar -czf "dist/${TAR}" -C "${TDIR}" mpris-bridged mpris-bridgec

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_FOR_RELEASE }}
